---
name: Rust tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    container: "nisectuni/qubip-ossl-rust-runner:latest-nix"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Check rustc version"
        run: rustc --version
      - name: "Check cargo version"
        run: cargo --version
      - name: "Check openssl version"
        run: openssl version -a
      - run: cargo fmt -- --check
  test-code:
    runs-on: ubuntu-latest
    container: "nisectuni/qubip-ossl-rust-runner:latest-nix"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Check rustc version"
        run: rustc --version
      - name: "Check cargo version"
        run: cargo --version
      - name: "Check openssl version"
        run: openssl version -a
      - name: "Execute cargo test"
        run: cargo test